In [1]:
import numpy as np

In [3]:
array = np.arange(0,10)
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
array[0]

0

In [5]:
array[8]

8

In [6]:
array[5]

5

In [7]:
array[2:4]

array([2, 3])

In [8]:
array[:4]

array([0, 1, 2, 3])

In [9]:
array[:]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
array[5:]

array([5, 6, 7, 8, 9])

In [12]:
array2 = array.copy()
array2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
array2[0] = 1100

In [14]:
array2

array([1100,    1,    2,    3,    4,    5,    6,    7,    8,    9])

In [15]:
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])